/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrismMetaRecord extends org.jooq.impl.UpdatableRecordImpl<me.botsko.prism.database.tables.records.PrismMetaRecord> implements org.jooq.Record3<org.jooq.types.UInteger, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1378614238;

	/**
	 * Setter for <code>minecraft.prism_meta.id</code>. 
	 */
	public void setId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>minecraft.prism_meta.id</code>. 
	 */
	public org.jooq.types.UInteger getId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>minecraft.prism_meta.k</code>. 
	 */
	public void setK(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>minecraft.prism_meta.k</code>. 
	 */
	public java.lang.String getK() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>minecraft.prism_meta.v</code>. 
	 */
	public void setV(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>minecraft.prism_meta.v</code>. 
	 */
	public java.lang.String getV() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return me.botsko.prism.database.tables.PrismMeta.PRISM_META.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return me.botsko.prism.database.tables.PrismMeta.PRISM_META.K;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return me.botsko.prism.database.tables.PrismMeta.PRISM_META.V;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getK();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getV();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PrismMetaRecord
	 */
	public PrismMetaRecord() {
		super(me.botsko.prism.database.tables.PrismMeta.PRISM_META);
	}

	/**
	 * Create a detached, initialised PrismMetaRecord
	 */
	public PrismMetaRecord(org.jooq.types.UInteger id, java.lang.String k, java.lang.String v) {
		super(me.botsko.prism.database.tables.PrismMeta.PRISM_META);

		setValue(0, id);
		setValue(1, k);
		setValue(2, v);
	}
}
