/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrismWorldsRecord extends org.jooq.impl.UpdatableRecordImpl<me.botsko.prism.database.tables.records.PrismWorldsRecord> implements org.jooq.Record2<org.jooq.types.UInteger, java.lang.String> {

	private static final long serialVersionUID = 1458847409;

	/**
	 * Setter for <code>minecraft.prism_worlds.world_id</code>. 
	 */
	public void setWorldId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>minecraft.prism_worlds.world_id</code>. 
	 */
	public org.jooq.types.UInteger getWorldId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>minecraft.prism_worlds.world</code>. 
	 */
	public void setWorld(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>minecraft.prism_worlds.world</code>. 
	 */
	public java.lang.String getWorld() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS.WORLD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS.WORLD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getWorldId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getWorld();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PrismWorldsRecord
	 */
	public PrismWorldsRecord() {
		super(me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS);
	}

	/**
	 * Create a detached, initialised PrismWorldsRecord
	 */
	public PrismWorldsRecord(org.jooq.types.UInteger worldId, java.lang.String world) {
		super(me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS);

		setValue(0, worldId);
		setValue(1, world);
	}
}
