/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrismActionsRecord extends org.jooq.impl.UpdatableRecordImpl<me.botsko.prism.database.tables.records.PrismActionsRecord> implements org.jooq.Record2<org.jooq.types.UInteger, java.lang.String> {

	private static final long serialVersionUID = 1510970413;

	/**
	 * Setter for <code>minecraft.prism_actions.action_id</code>. 
	 */
	public void setActionId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>minecraft.prism_actions.action_id</code>. 
	 */
	public org.jooq.types.UInteger getActionId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>minecraft.prism_actions.action</code>. 
	 */
	public void setAction(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>minecraft.prism_actions.action</code>. 
	 */
	public java.lang.String getAction() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS.ACTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS.ACTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getActionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAction();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PrismActionsRecord
	 */
	public PrismActionsRecord() {
		super(me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS);
	}

	/**
	 * Create a detached, initialised PrismActionsRecord
	 */
	public PrismActionsRecord(org.jooq.types.UInteger actionId, java.lang.String action) {
		super(me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS);

		setValue(0, actionId);
		setValue(1, action);
	}
}
