/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrismDataRecord extends org.jooq.impl.UpdatableRecordImpl<me.botsko.prism.database.tables.records.PrismDataRecord> implements org.jooq.Record12<org.jooq.types.UInteger, org.jooq.types.UInteger, org.jooq.types.UInteger, org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1947319217;

	/**
	 * Setter for <code>minecraft.prism_data.id</code>. 
	 */
	public void setId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.id</code>. 
	 */
	public org.jooq.types.UInteger getId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>minecraft.prism_data.epoch</code>. 
	 */
	public void setEpoch(org.jooq.types.UInteger value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.epoch</code>. 
	 */
	public org.jooq.types.UInteger getEpoch() {
		return (org.jooq.types.UInteger) getValue(1);
	}

	/**
	 * Setter for <code>minecraft.prism_data.action_id</code>. 
	 */
	public void setActionId(org.jooq.types.UInteger value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.action_id</code>. 
	 */
	public org.jooq.types.UInteger getActionId() {
		return (org.jooq.types.UInteger) getValue(2);
	}

	/**
	 * Setter for <code>minecraft.prism_data.player_id</code>. 
	 */
	public void setPlayerId(org.jooq.types.UInteger value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.player_id</code>. 
	 */
	public org.jooq.types.UInteger getPlayerId() {
		return (org.jooq.types.UInteger) getValue(3);
	}

	/**
	 * Setter for <code>minecraft.prism_data.world_id</code>. 
	 */
	public void setWorldId(org.jooq.types.UInteger value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.world_id</code>. 
	 */
	public org.jooq.types.UInteger getWorldId() {
		return (org.jooq.types.UInteger) getValue(4);
	}

	/**
	 * Setter for <code>minecraft.prism_data.x</code>. 
	 */
	public void setX(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.x</code>. 
	 */
	public java.lang.Integer getX() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>minecraft.prism_data.y</code>. 
	 */
	public void setY(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.y</code>. 
	 */
	public java.lang.Integer getY() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>minecraft.prism_data.z</code>. 
	 */
	public void setZ(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.z</code>. 
	 */
	public java.lang.Integer getZ() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>minecraft.prism_data.block_id</code>. 
	 */
	public void setBlockId(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.block_id</code>. 
	 */
	public java.lang.Integer getBlockId() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>minecraft.prism_data.block_subid</code>. 
	 */
	public void setBlockSubid(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.block_subid</code>. 
	 */
	public java.lang.Integer getBlockSubid() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>minecraft.prism_data.old_block_id</code>. 
	 */
	public void setOldBlockId(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.old_block_id</code>. 
	 */
	public java.lang.Integer getOldBlockId() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>minecraft.prism_data.old_block_subid</code>. 
	 */
	public void setOldBlockSubid(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data.old_block_subid</code>. 
	 */
	public java.lang.Integer getOldBlockSubid() {
		return (java.lang.Integer) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<org.jooq.types.UInteger, org.jooq.types.UInteger, org.jooq.types.UInteger, org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<org.jooq.types.UInteger, org.jooq.types.UInteger, org.jooq.types.UInteger, org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field2() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.EPOCH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field3() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.ACTION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field4() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.PLAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field5() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.WORLD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.X;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.Y;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.Z;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.BLOCK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.BLOCK_SUBID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.OLD_BLOCK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return me.botsko.prism.database.tables.PrismData.PRISM_DATA.OLD_BLOCK_SUBID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value2() {
		return getEpoch();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value3() {
		return getActionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value4() {
		return getPlayerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value5() {
		return getWorldId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getX();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getY();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getZ();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getBlockId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getBlockSubid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getOldBlockId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getOldBlockSubid();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PrismDataRecord
	 */
	public PrismDataRecord() {
		super(me.botsko.prism.database.tables.PrismData.PRISM_DATA);
	}

	/**
	 * Create a detached, initialised PrismDataRecord
	 */
	public PrismDataRecord(org.jooq.types.UInteger id, org.jooq.types.UInteger epoch, org.jooq.types.UInteger actionId, org.jooq.types.UInteger playerId, org.jooq.types.UInteger worldId, java.lang.Integer x, java.lang.Integer y, java.lang.Integer z, java.lang.Integer blockId, java.lang.Integer blockSubid, java.lang.Integer oldBlockId, java.lang.Integer oldBlockSubid) {
		super(me.botsko.prism.database.tables.PrismData.PRISM_DATA);

		setValue(0, id);
		setValue(1, epoch);
		setValue(2, actionId);
		setValue(3, playerId);
		setValue(4, worldId);
		setValue(5, x);
		setValue(6, y);
		setValue(7, z);
		setValue(8, blockId);
		setValue(9, blockSubid);
		setValue(10, oldBlockId);
		setValue(11, oldBlockSubid);
	}
}
