/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrismPlayersRecord extends org.jooq.impl.UpdatableRecordImpl<me.botsko.prism.database.tables.records.PrismPlayersRecord> implements org.jooq.Record2<org.jooq.types.UInteger, java.lang.String> {

	private static final long serialVersionUID = 2019516793;

	/**
	 * Setter for <code>minecraft.prism_players.player_id</code>. 
	 */
	public void setPlayerId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>minecraft.prism_players.player_id</code>. 
	 */
	public org.jooq.types.UInteger getPlayerId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>minecraft.prism_players.player</code>. 
	 */
	public void setPlayer(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>minecraft.prism_players.player</code>. 
	 */
	public java.lang.String getPlayer() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<org.jooq.types.UInteger, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS.PLAYER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS.PLAYER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getPlayerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getPlayer();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PrismPlayersRecord
	 */
	public PrismPlayersRecord() {
		super(me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS);
	}

	/**
	 * Create a detached, initialised PrismPlayersRecord
	 */
	public PrismPlayersRecord(org.jooq.types.UInteger playerId, java.lang.String player) {
		super(me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS);

		setValue(0, playerId);
		setValue(1, player);
	}
}
