/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrismDataExtraRecord extends org.jooq.impl.UpdatableRecordImpl<me.botsko.prism.database.tables.records.PrismDataExtraRecord> implements org.jooq.Record4<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 718781170;

	/**
	 * Setter for <code>minecraft.prism_data_extra.extra_id</code>. 
	 */
	public void setExtraId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data_extra.extra_id</code>. 
	 */
	public org.jooq.types.UInteger getExtraId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>minecraft.prism_data_extra.data_id</code>. 
	 */
	public void setDataId(org.jooq.types.UInteger value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data_extra.data_id</code>. 
	 */
	public org.jooq.types.UInteger getDataId() {
		return (org.jooq.types.UInteger) getValue(1);
	}

	/**
	 * Setter for <code>minecraft.prism_data_extra.data</code>. 
	 */
	public void setData(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data_extra.data</code>. 
	 */
	public java.lang.String getData() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>minecraft.prism_data_extra.te_data</code>. 
	 */
	public void setTeData(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>minecraft.prism_data_extra.te_data</code>. 
	 */
	public java.lang.String getTeData() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<org.jooq.types.UInteger, org.jooq.types.UInteger, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA.EXTRA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field2() {
		return me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA.DATA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA.DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA.TE_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getExtraId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value2() {
		return getDataId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTeData();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PrismDataExtraRecord
	 */
	public PrismDataExtraRecord() {
		super(me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA);
	}

	/**
	 * Create a detached, initialised PrismDataExtraRecord
	 */
	public PrismDataExtraRecord(org.jooq.types.UInteger extraId, org.jooq.types.UInteger dataId, java.lang.String data, java.lang.String teData) {
		super(me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA);

		setValue(0, extraId);
		setValue(1, dataId);
		setValue(2, data);
		setValue(3, teData);
	}
}
