/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>minecraft</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<me.botsko.prism.database.tables.records.PrismActionsRecord, org.jooq.types.UInteger> IDENTITY_PRISM_ACTIONS = Identities0.IDENTITY_PRISM_ACTIONS;
	public static final org.jooq.Identity<me.botsko.prism.database.tables.records.PrismDataRecord, org.jooq.types.UInteger> IDENTITY_PRISM_DATA = Identities0.IDENTITY_PRISM_DATA;
	public static final org.jooq.Identity<me.botsko.prism.database.tables.records.PrismDataExtraRecord, org.jooq.types.UInteger> IDENTITY_PRISM_DATA_EXTRA = Identities0.IDENTITY_PRISM_DATA_EXTRA;
	public static final org.jooq.Identity<me.botsko.prism.database.tables.records.PrismMetaRecord, org.jooq.types.UInteger> IDENTITY_PRISM_META = Identities0.IDENTITY_PRISM_META;
	public static final org.jooq.Identity<me.botsko.prism.database.tables.records.PrismPlayersRecord, org.jooq.types.UInteger> IDENTITY_PRISM_PLAYERS = Identities0.IDENTITY_PRISM_PLAYERS;
	public static final org.jooq.Identity<me.botsko.prism.database.tables.records.PrismWorldsRecord, org.jooq.types.UInteger> IDENTITY_PRISM_WORLDS = Identities0.IDENTITY_PRISM_WORLDS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismActionsRecord> KEY_PRISM_ACTIONS_PRIMARY = UniqueKeys0.KEY_PRISM_ACTIONS_PRIMARY;
	public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismDataRecord> KEY_PRISM_DATA_PRIMARY = UniqueKeys0.KEY_PRISM_DATA_PRIMARY;
	public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismDataExtraRecord> KEY_PRISM_DATA_EXTRA_PRIMARY = UniqueKeys0.KEY_PRISM_DATA_EXTRA_PRIMARY;
	public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismMetaRecord> KEY_PRISM_META_PRIMARY = UniqueKeys0.KEY_PRISM_META_PRIMARY;
	public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismPlayersRecord> KEY_PRISM_PLAYERS_PRIMARY = UniqueKeys0.KEY_PRISM_PLAYERS_PRIMARY;
	public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismWorldsRecord> KEY_PRISM_WORLDS_PRIMARY = UniqueKeys0.KEY_PRISM_WORLDS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<me.botsko.prism.database.tables.records.PrismActionsRecord, org.jooq.types.UInteger> IDENTITY_PRISM_ACTIONS = createIdentity(me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS, me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS.ACTION_ID);
		public static org.jooq.Identity<me.botsko.prism.database.tables.records.PrismDataRecord, org.jooq.types.UInteger> IDENTITY_PRISM_DATA = createIdentity(me.botsko.prism.database.tables.PrismData.PRISM_DATA, me.botsko.prism.database.tables.PrismData.PRISM_DATA.ID);
		public static org.jooq.Identity<me.botsko.prism.database.tables.records.PrismDataExtraRecord, org.jooq.types.UInteger> IDENTITY_PRISM_DATA_EXTRA = createIdentity(me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA, me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA.EXTRA_ID);
		public static org.jooq.Identity<me.botsko.prism.database.tables.records.PrismMetaRecord, org.jooq.types.UInteger> IDENTITY_PRISM_META = createIdentity(me.botsko.prism.database.tables.PrismMeta.PRISM_META, me.botsko.prism.database.tables.PrismMeta.PRISM_META.ID);
		public static org.jooq.Identity<me.botsko.prism.database.tables.records.PrismPlayersRecord, org.jooq.types.UInteger> IDENTITY_PRISM_PLAYERS = createIdentity(me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS, me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS.PLAYER_ID);
		public static org.jooq.Identity<me.botsko.prism.database.tables.records.PrismWorldsRecord, org.jooq.types.UInteger> IDENTITY_PRISM_WORLDS = createIdentity(me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS, me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS.WORLD_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismActionsRecord> KEY_PRISM_ACTIONS_PRIMARY = createUniqueKey(me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS, me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS.ACTION_ID);
		public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismDataRecord> KEY_PRISM_DATA_PRIMARY = createUniqueKey(me.botsko.prism.database.tables.PrismData.PRISM_DATA, me.botsko.prism.database.tables.PrismData.PRISM_DATA.ID);
		public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismDataExtraRecord> KEY_PRISM_DATA_EXTRA_PRIMARY = createUniqueKey(me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA, me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA.EXTRA_ID);
		public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismMetaRecord> KEY_PRISM_META_PRIMARY = createUniqueKey(me.botsko.prism.database.tables.PrismMeta.PRISM_META, me.botsko.prism.database.tables.PrismMeta.PRISM_META.ID);
		public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismPlayersRecord> KEY_PRISM_PLAYERS_PRIMARY = createUniqueKey(me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS, me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS.PLAYER_ID);
		public static final org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismWorldsRecord> KEY_PRISM_WORLDS_PRIMARY = createUniqueKey(me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS, me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS.WORLD_ID);
	}
}
