/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Minecraft extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -706110213;

	/**
	 * The singleton instance of <code>minecraft</code>
	 */
	public static final Minecraft MINECRAFT = new Minecraft();

	/**
	 * No further instances allowed
	 */
	private Minecraft() {
		super("minecraft");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS,
			me.botsko.prism.database.tables.PrismData.PRISM_DATA,
			me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA,
			me.botsko.prism.database.tables.PrismMeta.PRISM_META,
			me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS,
			me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS);
	}
}
