/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in minecraft
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table minecraft.prism_actions
	 */
	public static final me.botsko.prism.database.tables.PrismActions PRISM_ACTIONS = me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS;

	/**
	 * The table minecraft.prism_data
	 */
	public static final me.botsko.prism.database.tables.PrismData PRISM_DATA = me.botsko.prism.database.tables.PrismData.PRISM_DATA;

	/**
	 * The table minecraft.prism_data_extra
	 */
	public static final me.botsko.prism.database.tables.PrismDataExtra PRISM_DATA_EXTRA = me.botsko.prism.database.tables.PrismDataExtra.PRISM_DATA_EXTRA;

	/**
	 * The table minecraft.prism_meta
	 */
	public static final me.botsko.prism.database.tables.PrismMeta PRISM_META = me.botsko.prism.database.tables.PrismMeta.PRISM_META;

	/**
	 * The table minecraft.prism_players
	 */
	public static final me.botsko.prism.database.tables.PrismPlayers PRISM_PLAYERS = me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS;

	/**
	 * The table minecraft.prism_worlds
	 */
	public static final me.botsko.prism.database.tables.PrismWorlds PRISM_WORLDS = me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS;
}
