/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrismWorlds extends org.jooq.impl.TableImpl<me.botsko.prism.database.tables.records.PrismWorldsRecord> {

	private static final long serialVersionUID = -473675674;

	/**
	 * The singleton instance of <code>minecraft.prism_worlds</code>
	 */
	public static final me.botsko.prism.database.tables.PrismWorlds PRISM_WORLDS = new me.botsko.prism.database.tables.PrismWorlds();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<me.botsko.prism.database.tables.records.PrismWorldsRecord> getRecordType() {
		return me.botsko.prism.database.tables.records.PrismWorldsRecord.class;
	}

	/**
	 * The column <code>minecraft.prism_worlds.world_id</code>. 
	 */
	public final org.jooq.TableField<me.botsko.prism.database.tables.records.PrismWorldsRecord, org.jooq.types.UInteger> WORLD_ID = createField("world_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this);

	/**
	 * The column <code>minecraft.prism_worlds.world</code>. 
	 */
	public final org.jooq.TableField<me.botsko.prism.database.tables.records.PrismWorldsRecord, java.lang.String> WORLD = createField("world", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * Create a <code>minecraft.prism_worlds</code> table reference
	 */
	public PrismWorlds() {
		super("prism_worlds", me.botsko.prism.database.Minecraft.MINECRAFT);
	}

	/**
	 * Create an aliased <code>minecraft.prism_worlds</code> table reference
	 */
	public PrismWorlds(java.lang.String alias) {
		super(alias, me.botsko.prism.database.Minecraft.MINECRAFT, me.botsko.prism.database.tables.PrismWorlds.PRISM_WORLDS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<me.botsko.prism.database.tables.records.PrismWorldsRecord, org.jooq.types.UInteger> getIdentity() {
		return me.botsko.prism.database.Keys.IDENTITY_PRISM_WORLDS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismWorldsRecord> getPrimaryKey() {
		return me.botsko.prism.database.Keys.KEY_PRISM_WORLDS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismWorldsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismWorldsRecord>>asList(me.botsko.prism.database.Keys.KEY_PRISM_WORLDS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public me.botsko.prism.database.tables.PrismWorlds as(java.lang.String alias) {
		return new me.botsko.prism.database.tables.PrismWorlds(alias);
	}
}
