/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrismPlayers extends org.jooq.impl.TableImpl<me.botsko.prism.database.tables.records.PrismPlayersRecord> {

	private static final long serialVersionUID = -1930374874;

	/**
	 * The singleton instance of <code>minecraft.prism_players</code>
	 */
	public static final me.botsko.prism.database.tables.PrismPlayers PRISM_PLAYERS = new me.botsko.prism.database.tables.PrismPlayers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<me.botsko.prism.database.tables.records.PrismPlayersRecord> getRecordType() {
		return me.botsko.prism.database.tables.records.PrismPlayersRecord.class;
	}

	/**
	 * The column <code>minecraft.prism_players.player_id</code>. 
	 */
	public final org.jooq.TableField<me.botsko.prism.database.tables.records.PrismPlayersRecord, org.jooq.types.UInteger> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this);

	/**
	 * The column <code>minecraft.prism_players.player</code>. 
	 */
	public final org.jooq.TableField<me.botsko.prism.database.tables.records.PrismPlayersRecord, java.lang.String> PLAYER = createField("player", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this);

	/**
	 * Create a <code>minecraft.prism_players</code> table reference
	 */
	public PrismPlayers() {
		super("prism_players", me.botsko.prism.database.Minecraft.MINECRAFT);
	}

	/**
	 * Create an aliased <code>minecraft.prism_players</code> table reference
	 */
	public PrismPlayers(java.lang.String alias) {
		super(alias, me.botsko.prism.database.Minecraft.MINECRAFT, me.botsko.prism.database.tables.PrismPlayers.PRISM_PLAYERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<me.botsko.prism.database.tables.records.PrismPlayersRecord, org.jooq.types.UInteger> getIdentity() {
		return me.botsko.prism.database.Keys.IDENTITY_PRISM_PLAYERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismPlayersRecord> getPrimaryKey() {
		return me.botsko.prism.database.Keys.KEY_PRISM_PLAYERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismPlayersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismPlayersRecord>>asList(me.botsko.prism.database.Keys.KEY_PRISM_PLAYERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public me.botsko.prism.database.tables.PrismPlayers as(java.lang.String alias) {
		return new me.botsko.prism.database.tables.PrismPlayers(alias);
	}
}
