/**
 * This class is generated by jOOQ
 */
package me.botsko.prism.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrismActions extends org.jooq.impl.TableImpl<me.botsko.prism.database.tables.records.PrismActionsRecord> {

	private static final long serialVersionUID = -827944871;

	/**
	 * The singleton instance of <code>minecraft.prism_actions</code>
	 */
	public static final me.botsko.prism.database.tables.PrismActions PRISM_ACTIONS = new me.botsko.prism.database.tables.PrismActions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<me.botsko.prism.database.tables.records.PrismActionsRecord> getRecordType() {
		return me.botsko.prism.database.tables.records.PrismActionsRecord.class;
	}

	/**
	 * The column <code>minecraft.prism_actions.action_id</code>. 
	 */
	public final org.jooq.TableField<me.botsko.prism.database.tables.records.PrismActionsRecord, org.jooq.types.UInteger> ACTION_ID = createField("action_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this);

	/**
	 * The column <code>minecraft.prism_actions.action</code>. 
	 */
	public final org.jooq.TableField<me.botsko.prism.database.tables.records.PrismActionsRecord, java.lang.String> ACTION = createField("action", org.jooq.impl.SQLDataType.VARCHAR.length(25).nullable(false), this);

	/**
	 * Create a <code>minecraft.prism_actions</code> table reference
	 */
	public PrismActions() {
		super("prism_actions", me.botsko.prism.database.Minecraft.MINECRAFT);
	}

	/**
	 * Create an aliased <code>minecraft.prism_actions</code> table reference
	 */
	public PrismActions(java.lang.String alias) {
		super(alias, me.botsko.prism.database.Minecraft.MINECRAFT, me.botsko.prism.database.tables.PrismActions.PRISM_ACTIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<me.botsko.prism.database.tables.records.PrismActionsRecord, org.jooq.types.UInteger> getIdentity() {
		return me.botsko.prism.database.Keys.IDENTITY_PRISM_ACTIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismActionsRecord> getPrimaryKey() {
		return me.botsko.prism.database.Keys.KEY_PRISM_ACTIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismActionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<me.botsko.prism.database.tables.records.PrismActionsRecord>>asList(me.botsko.prism.database.Keys.KEY_PRISM_ACTIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public me.botsko.prism.database.tables.PrismActions as(java.lang.String alias) {
		return new me.botsko.prism.database.tables.PrismActions(alias);
	}
}
